version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./prisma/db:/app/prisma/dev.db
      - .env:/app/.env
    env_file:
      - .env
    environment:
      NODE_ENV: development
    command: npm run dev
