name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "file:./tmp/test.db"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
      - name: Use .env.test as .env
        run: cp .env.test .env

      - name: Create tmp directory for SQLite
        run: mkdir -p ./tmp

      - name: Migrate and Seed DB
        run: npx prisma migrate deploy && npx prisma db seed

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test
